### ISSUE TITLE
syntax error breaking tests

### ISSUE THREAD

**Issue by jd2rogers2** [learn-co-curriculum/js-principles-scope-chain-code-along#23]
student had correct code but tests failed
all tests except the last one passed, then when we put the below code in (nearly identical to solution's) it broke all tests
they were working in the downloaded IDE on windows
solution passed fine for me locally on mac

students breaking code
```
function attemptTwoFavoriteCustomers() {
  let favoriteCustomer = 'someone';
  favoriteCustomer = 'someone else';
}
```

learn errors
```
declare customerName to be bob in global scope
returns the customerName ‣
AssertionError: expected undefined to equal 'bob'
    at Context.<anonymous> (test/indexTest.js:5:38)
upperCaseCustomerName()
returns the customerName ‣
AssertionError: expected undefined to equal 'bob'
    at Context.<anonymous> (test/indexTest.js:11:38)
setBestCustomer()
setBestCustomer ‣
TypeError: window.setBestCustomer is not a function
    at Context.<anonymous> (test/indexTest.js:19:14)
overWriteBestCustomer()
overwrites the best customer ‣
ReferenceError: overWriteBestCustomer is not defined
    at Context.<anonymous> (test/indexTest.js:26:7)
reassignLeastFavorite
unsuccessfully tries to reassign the least favorite customer ‣
ReferenceError: changeLeastFavoriteCustomer is not defined
    at Context.<anonymous> (test/indexTest.js:33:14)
attemptTwoFavoriteCustomers
unsuccessfully tries to declare favoriteCustomer with let two times ‣
ReferenceError: attemptTwoFavoriteCustomers is not defined
    at Context.<anonymous> (test/indexTest.js:39:14)
```

**Comment by nsmmrs** [comment]
I just ran into the same error, but I don't think the above example would reproduce the problem.

With the following code (last function is identical to above) will, as expected, cause all tests except the final one to pass. The final test expects a syntax error to be raised in `attemptTwoFavoriteCustomers()`, but there is no syntax error so far, as `let` variables can be reassigned.

```
var customerName = "bob";
const leastFavoriteCustomer = "lemons";

function upperCaseCustomerName() {
  customerName = customerName.toUpperCase();
}

function setBestCustomer() {
  bestCustomer = "not bob";
}

function overWriteBestCustomer(message) {
  bestCustomer = message;
}

function changeLeastFavoriteCustomer() {
  leastFavoriteCustomer = "bob";
}

function attemptTwoFavoriteCustomers() {
  let favoriteCustomer = 'someone';
  favoriteCustomer = 'someone else';
}
```

Once `attemptTwoFavoriteCustomers()` is updated according to the lesson requirements (this is identical to the solution branch), everything in the file becomes undefined, causing all tests to fail.

```
function attemptTwoFavoriteCustomers() {
  let favoriteCustomer = 'someone';
  let favoriteCustomer = 'someone else';
}
```

I'm not familiar with JavaScript tooling, but my guess is there's a pre-processor that is watching and linting the file, which outputs a blank file on encountering the syntax error (I've had similar problems with SASS files which contained syntax errors).

**Comment by jonfoster9999** [comment]
I also just ran into this. I told the student to comment out the related test and move on. He was doing everything right and got the point about not being able to declare the same var twice in the same scope.
